### ISSUE TITLE
can't run create-config

### ISSUE THREAD

**Issue by mircealungu** [Perlten/MT-diagrams#11]
➜  api git:(master) ✗ mt-diagrams create-config
Traceback (most recent call last):
  File "/opt/homebrew/bin/mt-diagrams", line 5, in <module>
    from src.cli_interface import main
  File "/opt/homebrew/lib/python3.9/site-packages/src/cli_interface.py", line 10, in <module>
    from src.core.bt_graph import BTGraph
  File "/opt/homebrew/lib/python3.9/site-packages/src/core/bt_graph.py", line 6, in <module>
    from src.core.bt_file import BTFile, get_imported_modules
  File "/opt/homebrew/lib/python3.9/site-packages/src/core/bt_file.py", line 10, in <module>
    class BTFile:
  File "/opt/homebrew/lib/python3.9/site-packages/src/core/bt_file.py", line 41, in BTFile
    def module_path(self) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

➜  api git:(master) ✗ python --version
Python 3.9.16

Is this a matter of Python version? What version do you expect?

**Comment by Perlten** [comment]
We have specified in the pip package that we use 3.10, but we should add that to the readme as well :)

**Comment by mircealungu** [comment]
Python 3.10 seems to be released in 2023? 
How hard would it be to make it compatible with Python 3.9? You can't lose potential users because they don't have the very latest version of Python.

**Comment by Perlten** [comment]
It would be pretty easy do make it compatible with 3.9 since all we use from 3.10 are some type hinting features. 3.9 is on the backlog :)

**Comment by Perlten** [comment]
It is now 3.9 compatible
